---
- hosts: all
  become: yes
  vars_files:
    - /home/soham/Documents/learn/ansible/mediawiki-ansible/vars/mariadb_vars.yaml

  roles:
    - { role: geerlingguy.mysql }
    #    - role: geerlingguy.mysql

