---
- hosts: all
  become: yes
  vars_files:
    - vars/package_vars.yaml

  tasks:
    - name: Attempt to install packages if for some reason they were not installed with cloudinit
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - httpd-2.4.6-93.el7.centos
        - php-5.4.16-48.el7
        - php-mysql-5.4.16-48.el7
        - php-gd-5.4.16-48.el7
        - php-xml-5.4.16-48.el7
        - mariadb-server-5.5.65-1.el7
        - php-mbstring-5.4.16-48.el7
        - wget-1.14-18.el7_6.1
        - vim-enhanced-7.4.629-6.el7
        - python2-pip-8.1.2-12.el7
      tags: [ 'install_packages' ]
      register: install_packages

    - name: Install PyMySQL module with pip
      pip:
        name: pymysql
        state: present

    - name: Find out which packages were installed
      debug: var=install_packages

      #    - name: As a test, dump all variables in the playbook
      #      debug: var="hostvars[inventory_hostname]"
